export const GET_POST = 'GET_POST';
export const GET_POST_PENDING = 'GET_POST_PENDING';
export const GET_POST_FULFILLED = 'GET_POST_FULFILLED';
export const GET_POST_REJECTED = 'GET_POST_REJECTED';

export const GET_AUTHOR = 'GET_AUTHOR';
export const GET_AUTHOR_PENDING = 'GET_AUTHOR_PENDING';
export const GET_AUTHOR_FULFILLED = 'GET_AUTHOR_FULFILLED';
export const GET_AUTHOR_REJECTED = 'GET_AUTHOR_REJECTED';
